### ISSUE TITLE
Keys not sent to panel

### ISSUE THREAD

**Issue by nitej** [TANC-security/keypad-firmware#11]
I cannot seem to get the atmega to send key commands to the panel. I can see and decode messages sent from the panel to the keypads, but the commands seem to never leave the "to panel" buffer. The TT+KPADDR command works fine and I have changed the keypad address of the atmega to be different from the other keypad attached to the Vista 20p. Any idea what is causing this? What signals from the panel does the atmega look for to send data back to the panel? Is the communication code (to send data back to the panel) sensitive the clock speed of the uC?

I am using the following:
Vista 20p panel w/ 6160RF keypad (on address 16)
Uno (or a breadboard atmega 328p running at 8Mhz, tried both)
Using transistors as described in the readme for level shifting.
Atmega keypad address = 18

Thanks for you help.

**Comment by ghost** [comment]
Use Keypad Address 16 and on your IDE Serial Monitor, make sure you have Send CR on Enter enabled as you need the CR to end the command in serial monitor.  One other thing, I was only able to get the PC817 opto coupler to work.   I posted a wiring diagram on the only project https://github.com/markkimsal/homesecurity/issues/8  That x1 resistor should be a 10K pull down.

**Comment by nitej** [comment]
I've got the settings for sending commands from the computer to the arduino (since i can change the keypad address with the TT+ command). Is there any reason for using the address 16 vs others (since I usually put a real keypad on the lowest address)?

**Comment by ghost** [comment]
The panel has to have that keypad address enabled. I think they usually only have the active keypads enabled so 16 being the first keypad address will work but others may or may not work depending if your panel has that address enabled. There is a command you can run to check to see what address are enabled on the keypad but cant remember what the was.   16 should work and there is no issue with your keypad on same address as the arduino.

**Comment by ghost** [comment]
Here is an updated wiring diagram that works for me.
![Arduino-to-Ademco-Pinpad-1](https://user-images.githubusercontent.com/22331244/55650882-ce0cbf00-579b-11e9-9d38-cdfe997f84d8.png)

**Comment by bokumura** [comment]
Do you really need the 1N400X diode on the output to the keypad?

**Comment by ghost** [comment]
It will work without the diode but I had some strange issues on the data out so I put that in the circuit.  Not sure if it was the solution or not but left it in.

**Comment by nitej** [comment]
I was able to get it working by using a optocoupler on arduino tx to panel rx signal. Not sure why a 2n4401 works in the panel tx to arduino rx signal but not on the other. Thanks for the suggestion. It really helped me pinpoint the issue.
