### ISSUE TITLE
Update for LRR

### ISSUE THREAD

**Issue by ghost** [TANC-security/keypad-firmware#2]
For the section of code
//Long Range Radio (LRR)
if ((uint8_t)x == 0xF9) {

and the entire void on_lrr function

Should they not be encapsulated in the #ifdef LRR_SUPERVISOR so that they will be excluded from the build and save on memory if the LRR F9 data is not required?

**Comment by markkimsal** [comment]
LRR_SUPERVISOR determines whether or not the Arduino will try to act like an IP/GSM module by responding to required heartbeat messages.  F9 messages provide useful event info, like which user disarmed the system or which zone triggered an alarm.

**Comment by ghost** [comment]
I am not getting any F9 messages so I think it is disabled on my panel.   For my project I really dont need that extra data so I will just exclude that to same some memory.  Thanks
