### ISSUE TITLE
Software Serial Interupts

### ISSUE THREAD

**Issue by ghost** [TANC-security/keypad-firmware#4]
Have a question regarding the Pin Change Interupt.   That code seems to be there for the Software Serial which I am not really familiar with.  Trying to use the WiFi101 shield and it is tripping up on that section of code.  If I remove this code section, the code will compile with the WiFi101.H library but the messaging to the panel stops.   
If I leave this section in and I add the WiFi101.H library, the compiler failes. Looking at the errors online, this is a known issue with Software Serial and WiFi101.  Could not see any workaround to make this work and I really do not know anything about the code section below.   I am assuming this code is fixed and has to stay and I will not be able to work with the WiFi101 shiled but would like your comment on that if that is true.

//Pin Change INTerrupts
#if defined(PCINT0_vect)
ISR(PCINT0_vect)
{
  on_pin_change();
}
#endif

#if defined(PCINT1_vect)
ISR(PCINT1_vect, ISR_ALIASOF(PCINT0_vect));
#endif

#if defined(PCINT2_vect)
ISR(PCINT2_vect, ISR_ALIASOF(PCINT0_vect));
#endif

#if defined(PCINT3_vect)
ISR(PCINT3_vect, ISR_ALIASOF(PCINT0_vect));
#endif

**Comment by ghost** [comment]
Digging more into this I can see this section is reqiured.   Moving over to the Mega, this code section will allow the WiFi101 librabry to complile and load.    But with Mega/WiFi101, the system loads and works but the WiFi goes haywire.   It will connect but just get garbage back to the console.   

I was able to trace the problem down to specifically the on_pin_change()  function called from  the function #if defined(PCINT0_vect).   I think it has to do softwarserial using the interupts that the WiFi101 shield needs to operate correctly.

**Comment by markkimsal** [comment]
These are just grabbing all the available interrupts so that any pin can be used for the software serial and the tx and rx can be changed in the config.h.

> ISR (PCINT0_vect) pin change interrupt for D8 to D13
> ISR (PCINT1_vect) pin change interrupt for A0 to A5
> ISR (PCINT2_vect) pin change interrupt for D0 to D7

https://playground.arduino.cc/Main/PinChangeInterrupt

Wifi101 needs SPI so pins 10-13.  Comment out the PCINT0_vect and make all the ALAISOF point to 1.

Then change the rx/tx pins in config.h

I guess these could be moved to config.h with more documentation and comments.
