### ISSUE TITLE
Display Message Dropping first Char

### ISSUE THREAD

**Issue by ghost** [TANC-security/keypad-firmware#5]
I am stumped on this one and it is driving me bonkers.
Trying to capture the text going to the display and sending that to a String
For some reason the first letter of the display message will drop.  Let that same message loop and after a while then I start getting the first letter again.  New message will come and drop the first letter of the display message and then it will come back if that same message loops.
Example
Display message in the JSON shows "ARMED ***AWAY***May Exit Now  01"
When I capture that to string I get "RMED ***AWAY***May Exit Now  01"
or
JSON message "FAULT 01"
String gets "AULT 01"
Let that message stay and after 5 or so repeats my string will get "FAULT 01"

Here is my modified code.  The JSON is commented out and replaced with my String.   If I left the JSON in as well I would always see the first letter of the display message.  The Display1 string also drops the first letter as well and will get it after a few repeats like the OutStr
```
String OutStr = "D";
for (int x = 0; x <= 10 ; x++) {
    switch ( x ) {
case 6:
                if ( (cbuf[x] & BIT_MASK_BYTE1_BEEP ) > 0 ) {
                    //Serial.print(F(","));
                    //Serial.print(F(" \"beep\": \""));
                    //print_hex( cbuf[x], 8);
                    //Serial.print(F("\""));
                    OutStr += "T";
                }else{
                    OutStr += "F";
                }
                break;
            case 7:
                //Serial.print(sep);
                if ( (cbuf[x] & BIT_MASK_BYTE2_ARMED_HOME ) ) {
                    //Serial.print(F("\"ARMED_STAY\": true"));
                    OutStr += "T";
                }else{
                    //Serial.print(F("\"ARMED_STAY\": false"));
                    OutStr += "F";
                }
                if ( (cbuf[x] & BIT_MASK_BYTE2_LOW_BAT ) ) {
                    //Serial.print(sep);
                    //Serial.print(F("\"low_batt\": true"));
                    OutStr += "T";
                }else{
                    OutStr += "F";
                }     

                //Serial.print(sep);
                if ( (cbuf[x] & BIT_MASK_BYTE2_READY )) {
                    //Serial.print(F("\"READY\": \"true\""));
                    OutStr += "T";
                } else {
                    //Serial.print(F("\"READY\": \"false\""));
                    OutStr += "F";
                }
                break;
            case 8:
				        //Serial.print(sep);
                if ( (cbuf[x] & BIT_MASK_BYTE3_CHIME_MODE ) ) {
                    //Serial.print(F("\"chime\": \"on\""));
                    OutStr += "T";
                } else {
                    //Serial.print(F("\"chime\": \"off\""));
                    OutStr += "F";
                }

                if ( (cbuf[x] & BIT_MASK_BYTE3_BYPASS ) ) {
					          //Serial.print(sep);
                    //Serial.print(F("\"bypass_zone\": true"));
                    OutStr += "T";
                }else{
                    OutStr += "F";
                }

				        //Serial.print(sep);
                if ( (cbuf[x] & BIT_MASK_BYTE3_AC_POWER ) ) {
                    //Serial.print(F("\"ac_power\": \"on\""));
                    OutStr += "T";
                } else {
                    //Serial.print(F("\"ac_power\": \"off\""));
                    OutStr += "F";
                }

				        //Serial.print(sep);
                if ( (cbuf[x] & BIT_MASK_BYTE3_ARMED_AWAY ) > 0 ) {
                    //Serial.print(F("\"ARMED_AWAY\": true"));
                    OutStr += "T";
                } else {
                    //Serial.print(F("\"ARMED_AWAY\": false"));
                    OutStr += "F";
                }
                break;
            case 10:
                if ( cbuf[x] != 0x00 ) {
					        //Serial.print(sep);
                  //Serial.print(F("\"prompt_pos\": \""));
                  //Serial.print( (int)cbuf[x] );
                  //print_hex( cbuf[x], 8);
                  //Serial.print(F("\""));
                }

                break;
            }
	}
	//Serial.print(sep);
	//Serial.print(F("\"msg\": \""));
  OutStr += ":";
	for (int x = 12; x < *idx -1; x++) {
		if ((int)cbuf[x] < 32 || (int)cbuf[x] > 126) {
		    //don't print non printable ascii
		} else {
			//Serial.print(cbuf[x]);  
      if(MSGcnt < 16){
        Display1 = Display1 + cbuf[x];
        _**OutStr += cbuf[x];**_
        MSGcnt++;
      }else if(MSGcnt>15 && MSGcnt<32){
        Display2 = Display2 + cbuf[x];
        **_OutStr += cbuf[x];_**
        MSGcnt++;
      }
		}
		//TODO: fix timing
		//this is because there's a timing bug and we get an extra
		//1 bit in the most significant position
		if (cbuf[x] & 0x80) {
			cbuf[x] = cbuf[x] ^ 0x80;
			//Serial.print( cbuf[x] );
		}
	}
	//Serial.println(F("\"}"));

  //Outdata Data to Serial 
  Serial.println(OutStr);
```

**Comment by markkimsal** [comment]
Can you append to OutStr when the cbuf is out of ASCII range?  It could be a timing issue and the first character is either lower than 32 or above 126 because the value of the bits is shifted to the right or left one place.


```
		if ((int)cbuf[x] < 32 || (int)cbuf[x] > 126) {
		    Display1 += '_';
                    OutStr += '_';
		} else {
```
If you disable the wifi shield part of the code does this still happen?  (could be some kind of interrupt collision)

**Comment by ghost** [comment]
Here is the strange part, Serial.print(cbuf[x]) prints the character just fine.  In the sample below, the Serial.println prints the first char to the console just fine like the F in FAULT but the display and outstr stings drops the first letter for the first 5 messages and then gets the letter after a while.  It has to be a timing issue but no clue why cbuf would print to console and not to string for the first letter.  I have all the network/Wifi removed and nothing else added but base code.  Even the LRR is commented out. 
 if(MSGcnt < 16){
        Serial.print(cbuf[x]);   // This Works and prints to console
        Display1 = Display1 + cbuf[x];  //First letter will drop
          OutStr += cbuf[x];
        MSGcnt++;
      }else if(MSGcnt>15 && MSGcnt<32){
        Serial.print(cbuf[x]);
        Display2 = Display2 + cbuf[x];
        OutStr += cbuf[x];
        MSGcnt++;
      }

**Comment by markkimsal** [comment]
It might be low memory.  But, not sure why it would fix itself after a while.

You could try using `String::reserve(int size)` to allocate enough memory for the final string right away.

```
String Display = "";
Display.reserve(45);
```

Something like that might reduce fragmentation.

If you're able to `Serial.print(cbuf[x])` then it is not a timing problem.  I don't know what it is, but it's probably a low-memory / String class problem.

Why bother with String concats?  If `Serial.print()` works, then just use it.

**Comment by ghost** [comment]
Arghh.  Removed the concat string and did straight up Serial.print(cbuf[x]); and I am still dropping the firs letter of the message for the first 4 repeats and get the first letter on the 5th message repeat.  Seems consistent with tht 5th messgae.  Change in message always resets that back to 1 and drops the first letter.   Back to some sort of timing issue I need to track down.

**Comment by ghost** [comment]
And the problem is in the Serial Console as well so not just a problem with the serial COM to the second network arduino.  At this point I am closing this issue as I put in hours trying to figure this one out.   I am just going to handle it with the http post to the web API and add the missing letter since it is predictable based on the message.

**Comment by ghost** [comment]
So I had to give it one last go and what I found was cbuf[12] the first char in display message was getting the wrong value so the filter in the message out put was filtering it out.
" "  found dec -96 should be 32
"A" found dec -63 should be 65
"D" found dec -60 should be 68
"F" found dec -58 should be 70
So I added this to solve the problem.  Not sure why the char is getting invalid characters sometimes but it is always consistent in the invalid char so I am able to replace it.
if(cbuf[12] == -96){
    cbuf[12] = 32;
  }else if(cbuf[12] == -58){
    cbuf[12] = 70;
  }else if(cbuf[12] == -63){
    cbuf[12] = 65;
  }else if(cbuf[12] == -60){
    cbuf[12] = 68;
  }

**Comment by ghost** [comment]
I guess I could have also done it cbuf[12] = cbuf[12] +128 as it shifted down by 128

**Comment by markkimsal** [comment]
128 is 0x80

This code snippet tries to remove the highest bit if it is 1.  For me, this only happened to the first character of the second line of text.
```
        //1 bit in the most significant position
        if (cbuf[x] & 0x80) { 
            cbuf[x] = cbuf[x] ^ 0x80;                                                                                                                                 
            Serial.print( cbuf[x] );
        } 
```

**Comment by ghost** [comment]
That was it.   I moved that snippet of code up to the top before my loops and it fixed the issue with the first char.
